### ISSUE TITLE
executing brew info from within puppet fails, but doing it manually in the shell works

### ISSUE THREAD

**Issue by farebers** [TheKevJames/puppet-homebrew#100]
the symptom is:

```
Debug: Executing with uid=501 gid=20: '/usr/local/bin/brew info imagemagick'
Error: Could not find package: imagemagick
Error: /Stage[main]/Main/Node[myhost.foo.bar]/Package[imagemagick]/ensure: change from absent to present failed: Could not find package: imagemagick
```

but when I do it as the 501:20 user in his shell it works fine.

Also it works fine if I modify lib/puppet/provider/package/brew.rb: line 18 combine = true instead of false. (Must cd to $HOME of the 501 user then when executing puppet agent.)

Any hint for me?

Thank you!

**Comment by jordigg** [comment]
Does it work without modifying the code but still inside the $home of the user?

That is a known limitation while using brew via Puppet. Puppet will try and run from whichever folder you are in when you execute the command. While running from a daemon all is fine. If you do it manually and you are on a folder that the brew user doesn't have permissions to run from, it will fail. You'll need to change the folder or use /tmp for example.

Would be nice to execute all brew commands from /tmp by default for example to ensure all users can run correctly regardless.

Need to check on this error, I haven't come across myself.

**Comment by farebers** [comment]
wow yes it works! Hadn't thought of testing it this way. Thank you!
