### ISSUE TITLE
Keep brew up-to-date

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/puppet-homebrew#12]
Run `brew update` and `brew cask update` now and then.

**Comment by jordigg** [comment]
This is easy to implement, should we do it or should we leave it to the user to run it manually since brew doesn't pin versions?

**Comment by TheKevJames** [comment]
Looks like other puppet package managers do it like this: https://github.com/puppetlabs/puppetlabs-apt#update-the-list-of-packages

**Comment by loyaltyarm** [comment]
Brew does this automatically as of 1.0 on each run, would this still be needed (for casks maybe)?

**Comment by TheKevJames** [comment]
Closing due to auto-update behaviour that's been implemented in brew and brewcask since forever.
