### ISSUE TITLE
Dependency and Compatibility Versions

### ISSUE THREAD

**Issue by rhandimartin** [TheKevJames/puppet-homebrew#151]
There is an inconsistency here where the suggested compatibility is < 7.0.0 but the stdlib dependency is <5.0.0.

**Comment by TheKevJames** [comment]
Oh wow, not sure how I missed that -- great catch! Fixed, and uploaded as [v1.9.1](https://forge.puppet.com/modules/thekevjames/homebrew/1.9.1). Thanks!
