### ISSUE TITLE
has_compiler fact not set

### ISSUE THREAD

**Issue by amosshapira** [TheKevJames/puppet-homebrew#17]
I'm trying to use version 1.3.0 of the module (taken from the Puppet Forge) on OSX 10.11 with Puppet 3.8.6 and Facter 2.4.6 and hit a problem where the `confine` in `lib/facter/has_compiler.rb` don't trigger any of the settings, causing `has_compiler` to be set to `nil` and the module tries to install the command line tools and Homebrew when it shouldn't (they are already available on the sever).

I added the following debug prints to `has_compiler.rb`:

```
--- has_compiler.rb	2016-02-03 14:11:58.000000000 +1100
+++ .../has_compiler.rb	2016-04-19 10:49:10.000000000 +1000
@@ -1,12 +1,15 @@
 Facter.add(:has_compiler) do
+  puts("Inside has_compiler, operatingsystem: #{Facter.value(:operatingsystem)}; macosx_productversion_major: #{Facter.value(:macosx_productversion_major)}")
   confine :operatingsystem => :darwin
   setcode do
+    puts('Inside :operatingsystem => :darwin')
     File.exists?('/usr/bin/cc') || system('/usr/bin/xcrun -find cc >/dev/null 2>&1')
   end

   # /usr/bin/cc exists in Mavericks, but it's not real
   confine :macosx_productversion_major => '10.9'
   setcode do
+    puts('Inside :macosx_productversion_majon => 10.9')
     (File.exists?('/Applications/Xcode.app') or File.exists?('/Library/Developer/CommandLineTools/')) and
     (File.exists?('/usr/bin/cc') || system('/usr/bin/xcrun -find cc >/dev/null 2>&1'))
   end
```
And when I run `puppet apply` I can see that the `confine` don't match:
```
$ puppet apply --verbose --modulepath modules -e 'class { "homebrew": }'
...
Inside has_compiler, operatingsystem: Darwin; macosx_productversion_major: 10.11
Warning: Config file /Users/ashapira/.puppet/hiera.yaml not found, using Hiera defaults
Notice: Scope(Class[Homebrew::Compiler]): Installing Command Line Tools.
...
```
And of course it fails because it tries to download a `.dmg` file from a URL which doesn't exist.

Any guidance on how can I get around this?

Thanks.

**Comment by TheKevJames** [comment]
Hey! I don't have the time at the moment to dive into exactly why this happens, but I've worked around the issue for 1.3.1. If you update to v1.3.1, it should avoid trying to download and install the package. If the issue persists, please let me know.

Leaving this issue open as a TODO.

**Comment by amosshapira** [comment]
Thanks for the quick response.

I now get:
```
Error: Unknown function warn at .../modules/homebrew/manifests/compiler.pp:19 on node ...
```
(repeats twice)
Where line 19 reads:
```
warn('No Command Line Tools detected and no download source set. If Command Line Tools is installed, this may be a false positive. If not, please set download sources or install manually.')
```
In any case - the provider still doesn't work because it doesn't set `$::has_compiler`.

**Comment by amosshapira** [comment]
One interesting point is that by commenting out the following, the first `confine :operatingsystem => :darwin` started matching:
```
  # /usr/bin/cc exists in Mavericks, but it's not real
#  confine :macosx_productversion_major => '10.9'
#  setcode do
#    (File.exists?('/Applications/Xcode.app') or File.exists?('/Library/Developer/CommandLineTools/')) and
#    (File.exists?('/usr/bin/cc') || system('/usr/bin/xcrun -find cc >/dev/null 2>&1'))
#  end
```
It now still fails on the missing `warn` function but at least a `puts` which I added inside the `confine` is now reached.

Perhaps this is something to do with setting `has_weight`?

**Comment by TheKevJames** [comment]
I think I have a fix; facter is annoying. Could you replace you `has_compiler.rb` file with
```
Facter.add(:has_compiler) do
  setcode do
    warn('Unsupported OS.')
    nil
  end
end

Facter.add(:has_compiler) do
  confine :operatingsystem => :darwin
  setcode do
    File.exists?('/usr/bin/cc') || system('/usr/bin/xcrun -find cc >/dev/null 2>&1')
  end
end

Facter.add(:has_compiler) do
  # /usr/bin/cc exists in Mavericks, but it's not real
  confine :operatingsystem => :darwin, :macosx_productversion_major => '10.9'
  setcode do
    (File.exists?('/Applications/Xcode.app') or File.exists?('/Library/Developer/CommandLineTools/')) and
    (File.exists?('/usr/bin/cc') || system('/usr/bin/xcrun -find cc >/dev/null 2>&1'))
  end
end
``` and let me know if that works out?

**Comment by TheKevJames** [comment]
(also: thanks for pointing out the `warn` issue. TIL puppet is not ruby; the puppet `warning` function maps to `warn` in ruby)

**Comment by amosshapira** [comment]
OK, I tried this and there are some mixed rerults:

1. `::has_compilter` is now set to `true`
2. its value isn't recognised as `true` even though it prints it that way. ie. here is the code after I added a couple of debug `warning` calls (and fixed `warn`):

```
class homebrew::compiler {

  warning("has_compiler: \"${::has_compiler}\"")
  if $::has_compiler == true {
    warning("has_compiler is true")
  } elsif versioncmp($::macosx_productversion_major, '10.7') < 0 {
    warning('Please install the Command Line Tools bundled with XCode manually!')
  } else {

    warning("has_compiler is not true and OSX is newer")
    if ($homebrew::command_line_tools_package and $homebrew::command_line_tools_source) {

      notice('Installing Command Line Tools.')

      package { $homebrew::command_line_tools_package:
        ensure   => present,
        provider => pkgdmg,
        source   => $homebrew::command_line_tools_source,
      }

    } else {
      warning('No Command Line Tools detected and no download source set. If Command Line Tools is installed, this may be a false positive. If not, please set download sources or install manually.')
    }

  }

}
```
And here is the output:
```
Warning: Scope(Class[Homebrew::Compiler]): has_compiler: "true"
Warning: Scope(Class[Homebrew::Compiler]): has_compiler is not true and OSX is newer
Warning: Scope(Class[Homebrew::Compiler]): No Command Line Tools detected and no download source set. If Command Line Tools is installed, this may be a false positive. If not, please set download sources or install manually.
```
The `$::has_compiler == true` seems to fail even though it prints `true` in the `warning` just before it. I suspect something about string vs. 'true' constant.

Changing this condition to:

```
  if $::has_compiler {
```
made the code pass, but I'd like to understand why it fails without this change (or actually, why do we need this empty `if` at all).

**Comment by TheKevJames** [comment]
Hmm, interestingly it "works for me" (tm) on OSX 10.10 with puppet 3.8.6 and facter 2.4.6. I don't have an OSX 10.11 box, I wonder if that's the problem. Sorry for this taking so long to resolve, it looks like puppet is treating the symbols differently than I am expecting... I will continue looking into this tomorrow.

My best guess as to why your change passes is since puppet is treating the true boolean as a string (?), and all non-empty strings are truthy, `if $::has_compiler` is thus truthy and succeeds. Unfortunately, we couldn't use that in the codebase since I suspect the string `"false"` would also be truthy... thus when you do not have a compiler, `if $::has_compiler` would _still_ be true.

As for why we need the if, we just don't want to either throw the pre-10.7 warning nor try to install the CLI tools if the compiler already exists on the path; trying to install a second version could lead to all sorts of unexpected behaviour.

Thanks for helping to track this down!

**Comment by amosshapira** [comment]
Yes I suspect something similar (about the "truthfulness" of "true" vs. "false").

My question is about the empty "if" - why not reverse it and wrap the other conditions inside, e.g.:
```
  warning("has_compiler: \"${::has_compiler}\"")
  if ! $::has_compiler {
    if versioncmp($::macosx_productversion_major, '10.7') < 0 {
      warning('Please install the Command Line Tools bundled with XCode manually!')
    } else {
    }
  }
```

**Comment by TheKevJames** [comment]
For a couple reasons; the first being that the codebase I forked this from did it that way :P The second being that I agree with it stylistically; nested if statements can quickly get out of control and are somewhat against the spirit of ruby, where `return unless condition` is the nicest way of doing things -- ie. rather than
```
if condition
   # SNIP ...
   return final_result
end
```
we prefer
```
return unless condition

# SNIP ...
return final_result
```

Clearly both do the same thing, but one is less nested and thus takes up less horizontal real-estate and is -- theoretically -- easier to read.

**Comment by TheKevJames** [comment]
Please test with #20 -- if that works for you, I'll go ahead and cut a new release.

**Comment by amosshapira** [comment]
Works.

I haven't started the Vagrant box from scratch because of time constraints (other parts of the Puppet manifest take ages and I'm digging other problems right now), but the module didn't show any of the problems it had before.

Thanks.

**Comment by TheKevJames** [comment]
Released as 1.3.2, should now be available on the Forge. Please let me know if you have any other issues!

**Comment by amosshapira** [comment]
I've updated to 1.3.2 and it works fine. Still have to see how it will behave when starting from scratch but I'll report this separately if it turns out to be a problem. Thanks very much for your response!

**Comment by TheKevJames** [comment]
Nice catch, fix for this will be in the next release (see PR #21). Thanks again!
