### ISSUE TITLE
Undefined method 'err' under PuppetServer 2.3.1

### ISSUE THREAD

**Issue by jordigg** [TheKevJames/puppet-homebrew#23]
Just updated my Puppet Server to 2.3.1 and got errors on the has_brew and has_compiler facts.

`error while resolving custom fact "has_brew": undefined method 'err' for #<Facter::Util::Resolution:0x0000000281b8c8>`

same for has_compiler. Is it maybe that errors should be handled, for example, by:
`rescue Facter::Core::Execution::ExecutionFailure
      'timeout!'`

Another question is, should we confine that custom_fact just to MacOSX?
`confine :kernel => "Darwin"`

**Comment by jordigg** [comment]
Just saw that you were already working on it on #22. What about using confine `:kernel => "Darwin"` to just tun it on Darwin nodes?

**Comment by TheKevJames** [comment]
There was some weirdness in `confine` that caused #17. I'm thinking just removing the err logs makes the most sense since actually trying to run the manifest on a non-Darwin system will already throw.

**Comment by TheKevJames** [comment]
Fixed in #22, released in 1.3.3.
