### ISSUE TITLE
`install_options` doesn't seem to work

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#25]
If I have a puppet manifest like so:

```puppet
# In site.pp:
Package {
  provider => homebrew
}

# Manifest code:
package {
    [
      'ack',
      'binutils'
    ]:
    install_options => [
      '--with-default-names',
    ],
  }
```

When I run puppet, the packages are not installed with default names. Running with `--debug` indicates that `--with-default-names` is not being passed to the underlying `brew install` command.

**Comment by TheKevJames** [comment]
Thanks for the report! Looks like the `install_options` feature wasn't quite as inheritable as I thought. Will be fixed in the next release.
