### ISSUE TITLE
Casks with checksum errors repeatedly attempt installation without erroring

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#27]
If there is a checksum error while installing a cask (or probably any other kind of Homebrew package/object, though I've only seen it with casks), this module will endlessly loop trying to re-install the cask. It will also report that it successfully installed the cask, despite the fact that the underlying command is returning an error and not doing the install. The following should be fixed:

- Cask checksum failures should directly or indirectly result in the cask's cached download (or all cached downloads) being cleared, either immediately after the checksum failure or on the start of the next Puppet run. 
- Cask installation failures due to checksum errors should be reported as Puppet apply failures (probably via exit code checking), rather than repeated attempts to install something.

**Comment by TheKevJames** [comment]
Thanks for the report! Fixed in #29, should be in the next release. I am still considering whether automatic deletion is "safe" enough to make the default behaviour. If you have any thoughts on this, please let me know.

**Comment by zbentley** [comment]
Given the simplicity of the fetching system in Homebrew, I strongly support automatic deletion as the default behavior. Honestly, I support it as the default behavior in _Homebrew_, but I haven't opened an issue there--maybe I should.

**Comment by zbentley** [comment]
Thanks!
