### ISSUE TITLE
Homebrew-cask should error when an app cannot be found due to a missing tap

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#34]
If I have a manifest (with no other taps) like this or similar:

```
Package {
  provider => homebrew,
  install_options => [
    '--with-default-names',
  ],
}
node default {
  package { "google-chrome-beta":
    provider => "brewcask",
    install_options => [
      "--appdir=/Applications"
    ]
  }
}
```

Puppet runs successfully and notifies that
`Notice: /Stage[main]/Main/Node[default]/Package[google-chrome-beta]/ensure: created`

However, the package is not installed in `/Applications`, `~/Applications`, or the Caskroom cache dir. This is because that particular cask (at the time of this writing) is available via the `caskroom/versions` tap.

If that tap is missing, the install should error.

**Comment by jordigg** [comment]
We should try to reproduce this again and see if the new settings with the error management catches this.

**Comment by TheKevJames** [comment]
Hmm, I can't replicate this, but that may not necessarily imply it was fixed. @zbentley do you still have this issue with the latest version of puppet-homebrew?

**Comment by zbentley** [comment]
This issue no longer occurs at the latest version. Thanks for all the hard work!
