### ISSUE TITLE
Homebrew-cask should error when an app cannot be installed due to a timeout

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#36]
If I try to install an app and it times out fetching from the server or otherwise has a communication error, Puppet reports that the app was successfully installed.

This module should probably check exit codes from homebrew-cask to ensure that this doesn't occur, and should definitely error if installation of a cask fails for any reason. This could probably be done by either doing more detailed checking of `brew cask install`'s results/output, or externally, by doing `brew cask info` after installation and/or statting files that homebrew-cask lists as "managed" by a cask. The latter route is tricky, though, since some casks don't have files listed in that section (or are preference panes etc).

**Comment by jordigg** [comment]
We should try to reproduce this again and see if the new settings with the error management catches this.

**Comment by zbentley** [comment]
I'm provisioning a lot of stuff this week. If I see any installation timeouts surfaced through puppet, I'll update this ticket.

**Comment by TheKevJames** [comment]
Any updates on this, @zbentley ?

**Comment by zbentley** [comment]
This correctly causes errors now. Thanks for all the hard work!
