### ISSUE TITLE
Module fails under puppet 3.8.6 installed from Homebrew

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/puppet-homebrew#7]
From @nexussafe:

Error is:

```
Debug: Prefetching brewcask resources for package
Debug: Executing '/usr/bin/stat -nf %Uu /usr/local/bin/brew'
Debug: Executing '/usr/bin/stat -nf %Ug /usr/local/bin/brew'
Debug: Executing '/usr/local/bin/brew cask list --versions'
Debug: Executing '/usr/bin/stat -nf %Uu /usr/local/bin/brew'
Debug: Executing '/usr/bin/stat -nf %Ug /usr/local/bin/brew'
Debug: Executing '/usr/local/bin/brew cask list --versions'
Debug: Executing '/usr/bin/stat -nf %Uu /usr/local/bin/brew'
Debug: Executing '/usr/bin/stat -nf %Ug /usr/local/bin/brew'
Debug: Executing '/usr/local/bin/brew cask install firefox'
Error: Could not find package firefox
Error: /Stage[main]/Main/Package[firefox]/ensure: change from absent to present failed: Could not find package firefox
```

Workaround is to call (eg. without owner change):

```
super(cmd, # No idea why
              :custom_environment => { 'HOME' => home })
```

User had installed brew manually, then `brew cask install puppet`.

```
$ ls -la /usr/local/bin/brew
-rwxr-xr-x  1 nexussafe  admin  656 Mar  8 17:46 /usr/local/bin/brew
$ stat -nf %Uu /usr/local/bin/brew
501%
$ stat -nf %Ug /usr/local/bin/brew
80%
$ id
uid=501(nexussafe) gid=20(staff) groups=20(staff),<SNIP>,80(admin),<SNIP>
$ which puppet
/usr/bin/puppet
$ puppet --version
3.8.6
```

See #2 for context.

**Comment by TheKevJames** [comment]
`brew cask install puppet` [source](https://github.com/caskroom/homebrew-cask/blob/master/Casks/puppet.rb)

**Comment by nexussafe** [comment]
If I run puppet with `sudo`, everything works

    $ sudo puppet apply --modulepath ./lib/modules setup.pp
    Notice: Compiled catalog for nexussafe-macbook-pro.local in environment production in 0.52 seconds
    Notice: /Stage[main]/Main/Package[thunderbird]/ensure: created
    Notice: Finished catalog run in 31.40 seconds

    $ puppet apply --modulepath ./lib/modules setup.pp
    Notice: Compiled catalog for nexussafe-macbook-pro.local in environment production in 0.52 seconds
    Error: Could not update: Could not find package thunderbird
    Error: /Stage[main]/Main/Package[thunderbird]/ensure: change from absent to latest failed: Could not update: Could not find package thunderbird
    Notice: Finished catalog run in 0.11 seconds

setup.pp looks as follows:

    if $::kernel == darwin {
      package {
        'thunderbird':
        ensure   => latest,
        provider => brewcask,
      }
    }

`lib/modules/` has `homebrew` folder that is dowloaded from puppetforge

**Comment by TheKevJames** [comment]
Interesting. AFAIK many puppet modules are written assuming they are being run by the root user, so you may want to make that your standard workflow. 

That said, this module should be easy enough to modify to run as non-root; I see two potential problem areas: the `su` @nexussafe brought up and most of `homebrew::install`, since puppet throws 

    Warning: Cannot manage ownership unless running as root

This is probably fixable.

Current guesses:
- `su`: check current user and only `su` if they are not the correct user (`facter {,g}id` is string). Group may be more iffy, but can probably be ignored?
- `homebrew::install`: might be dealt with by refactor to new standards? Check current puppet version compat to ensure nothing is lost there. If not, ownership could probably be managed iff user is privileged (how check?).

**Comment by TheKevJames** [comment]
I can no longer replicate this bug as of release 1.4.2. Closing this issue. If you continue to have problems, please let me know.
