### ISSUE TITLE
On Mac OS X 10.12, getting issue with parent provider not found

### ISSUE THREAD

**Issue by aholtventuretech** [TheKevJames/puppet-homebrew#73]
I am applying a puppet manifest locally using "puppet apply", and am running into a roadblock with the package provider not autoloading.

The exact error is:

"Could not autoload puppet/provider/package/brew: Could not find parent provider brewcommon of brew"

My suspicion is that it is trying to load each of the package providers alphabetically, which means brew would go first.  Any help with this would be greatly appreciated.

**Comment by aholtventuretech** [comment]
My suspicion was correct.

I renamed brewcommon.rb to a_brewcommon.rb (seen [here](https://github.com/aholtventuretech/puppet-homebrew/commit/721ea5dd5ebc1897ad28767d8b3e68911bbd0782), and the error went away

**Comment by TheKevJames** [comment]
Thanks for the bug report!

I finally found some other references to puppet loading some resources alphabetically. Great find on this, though I'm incredibly curious as to why we've never noticed this behavior before. We've had enough issues with the `brewcommon` stuff that I'll be removing it anyway, but if you have any idea why you might have come across this issue (version numbers are helpful, for puppet, puppet-homebrew, ruby, your OS, etc...; any non-default customizations you're running, etc), that'd be much appreciated.

**Comment by TheKevJames** [comment]
Hey @aholtventuretech! This issue should now be fixed in release 1.6.0 (just released on Puppet Forge). Please let me know if you have any further issues!
