### ISSUE TITLE
Allow the use of version parameter

### ISSUE THREAD

**Issue by jordigg** [TheKevJames/puppet-homebrew#81]
Brew allows now to install specific versions. Should we provide a parameter instead of asking the user to provide the name of the package with the versioning included?
https://github.com/Homebrew/brew/issues/620

**Comment by TheKevJames** [comment]
I've never actually bothered pinning a version, so let me know if I'm wrong, but shouldn't the code [here](https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/brew.rb#L69-L79) manage this? Usage should be as it is in [default puppet package modules](https://docs.puppet.com/puppet/latest/types/package.html#package-attribute-ensure), ie.

    package { "curl":
        ensure   => "v42,
        provider => brew,
    }

That said, it might be worth documenting this and adding a test.
