### ISSUE TITLE
Add tagged release for 1.6.0 to GitHub

### ISSUE THREAD

**Issue by zbentley** [TheKevJames/puppet-homebrew#84]
Some of the environments I use this module on don't have access to the Forge (we're working on it; #justcorporatethings), but do have access to GitHub. It's useful to be able to deploy new modules to them by selecting the same version tags we'd ask for in the Forge, but 1.6.0 isn't available as a tag on this GH repo. Could it be added?

Thanks!

Zac

**Comment by TheKevJames** [comment]
Hey, thanks for the heads up! Tag 1.6.0 has been created.
